Description of get_subsampled_shape
Home > code > get_subsampled_shape.m
get_subsampled_shape
PURPOSE
Read already subsampled file, if it exists
SYNOPSIS
function X = get_subsampled_shape(dir , id , N)
DESCRIPTION
Read already subsampled file, if it exists
If it doesnt or it does not have enough points, read original off file, subsample, save the subsampled file, and return subsample
CROSS-REFERENCE INFORMATION
This function calls:
subsample Subsample N points from V, using points in seed as starting seed
This function is called by:
clusterMapLowRes % set path and preparation
main %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
SOURCE CODE
function X = get_subsampled_shape(dir , id , N)
%Read already subsampled file, if it exists
%If it doesnt or it does not have enough points, read original off file, subsample, save the subsampled file, and return subsample
sub_off_fn = [ dir 'subsampled' filesep num2str(id) '.off' ];
off_fn     = [ dir 'original' filesep num2str(id) '.off' ];
if exist(sub_off_fn , 'file')
    [ X, tmp ]       = read_off( sub_off_fn );
    n_subsampled_pts = size(X, 2);
else
    X                = [];
    n_subsampled_pts = 0;
end
if (n_subsampled_pts < N)
    [V,F] = read_off( off_fn );
    ind   = subsample( V , N, X);
    X     = V ( :, ind );
    if( ~exist([dir filesep 'subsampled'], 'dir') )
        mkdir([dir filesep 'subsampled']);
    end
    write_off( sub_off_fn, X, [1 2 3]'); %write_off breaks if there are no faces
end
end