Description of jprocrustes
Home > code > jprocrustes.m
jprocrustes
PURPOSE
Computes the best rotation that when applied to
SYNOPSIS
function [R, d] = jprocrustes(x, y)
DESCRIPTION
Computes the best rotation that when applied to
y lies closest to x. No scaling.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
clusterReduceHighRes % set path and preparation
locgpd Local Generalized Procrustes Distance function
main %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
SOURCE CODE
function [R, d] = jprocrustes(x, y)
%Computes the best rotation that when applied to
%y lies closest to x. No scaling.
A = x*y';
[u,s,v]=svd(A);
R=u*v';
tmp = x-R*y;
d = sqrt(sum(sum(tmp.^2))); % Notice there IS the square root
end