Description of localize
Home > code > localize.m
localize
PURPOSE
Takes a global alignment and returns a pairwise one
SYNOPSIS
function pa = localize(ga)
DESCRIPTION
Takes a global alignment and returns a pairwise one
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
clusterMapHighRes % set path and preparation
main %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
temp_make_plots
SOURCE CODE
function pa = localize(ga)
%Takes a global alignment and returns a pairwise one
n = size(ga.R , 2);
a = 1; % the base
pa.R      = cell (n, n);
pa.P      = cell (n, n);
for ii = 1 : n
    for jj = 1 : n
        pa.R{ ii , jj } = ga.R{ ii }' * ga.R{ jj }  ;
        pa.P{ ii , jj } = ga.P{ jj }  * ga.P{ ii  }';
    end
end