Description of touch
Home > code > touch.m
touch
PURPOSE
TOUCH Summary of this function goes here
SYNOPSIS
function touch(dir_string)
DESCRIPTION
TOUCH Summary of this function goes here
   Detailed explanation goes here
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
clusterMapHighRes % set path and preparation
clusterMapLowRes % set path and preparation
main %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
SOURCE CODE
function touch(dir_string)
%TOUCH Summary of this function goes here
%   Detailed explanation goes here
if ~exist(dir_string, 'dir')
    mkdir(dir_string);
end
end