Description of upper_triangle
Home > code > upper_triangle.m
upper_triangle
PURPOSE
Creates a sparse square matrix with 1's above the diagonal,
SYNOPSIS
function M=upper_triangle(nn)
DESCRIPTION
Creates a sparse square matrix with 1's above the diagonal,
zero everywhere else
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
clusterMapHighRes % set path and preparation
clusterMapLowRes % set path and preparation
main %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
SOURCE CODE
function M=upper_triangle(nn)
%Creates a sparse square matrix with 1's above the diagonal,
%zero everywhere else
M=sparse(nn,nn);
[tmpi,tmpj]=ndgrid(1:nn,1:nn);
M(find(tmpj>tmpi))=1;
end